version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    expose:
      - 5432
    networks:
      - web-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
      - postgres
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web-network

  web:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "wait-for-it.sh -t 15 postgres:5432 && python manage.py makemigrations app && python manage.py migrate && python manage.py createsuperuser --noinput --username arsennazranov --email arsennazranov@gmail.com && daphne -p 8000 stock.asgi:application"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
