# Generated by Django 5.1.2 on 2024-11-14 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
