# Generated by Django 5.1.2 on 2024-11-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_chatmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
