name: Docker Compose CI

on:
  push:
    branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and run Docker Compose
      run: |
        docker-compose build
        docker-compose up -d

    - name: Make migrations
      run: |
        docker-compose run --rm -w /app web python manage.py makemigrations
        docker-compose run --rm -w /app web python manage.py migrate

    - name: Create superuser
      run: |
        docker-compose run --rm -w /app web python manage.py createsuperuser --noinput --username arsennazranov --email arsennazranov@gmail.com

    - name: Run Daphne server
      run: |
        docker-compose run --rm -w /app web daphne -p 8000 stock.asgi:application
